### ISSUE TITLE
loadavg

### ISSUE THREAD

**Issue by liuflylove666** [CtripCloud/docker-monitor-injector#1]
你好，请问injector对loadavg有做完善吗？

**Comment by jizhilong** [comment]
还没有。
我好奇问一下，你们是什么场景下会用到这个工具，而且需要对loadavg做处理呢？

**Comment by liuflylove666** [comment]
容器内部监控load值

**Comment by liuflylove666** [comment]
请问你有计划做这个吗？相关思路有吗？

**Comment by jizhilong** [comment]
不太确定你们的场景中，所需指标的确切物理意义是什么。从[linux文档](https://linux.die.net/man/5/proc)来看，`/proc/loadavg`各项值的含义是：

> The first three fields in this file are load average figures giving the number of jobs in the run queue (state R) or waiting for disk I/O (state D) averaged over 1, 5, and 15 minutes. They are the same as the load average numbers given by uptime(1) and other programs. The fourth field consists of two numbers separated by a slash (/). The first of these is the number of currently runnable kernel scheduling entities (processes, threads). The value after the slash is the number of kernel scheduling entities that currently exist on the system. The fifth field is the PID of the process that was most recently created on the system.

也就是整个系统内，最近一段时间内活跃的平均进程数。

切换到容器场景下的话，“整个系统内”的等价含义应该是这个容器的“cpu cgroup”内，或者这个容器的“pid namespace”内。能否为容器找到一段时间内的活跃进程数，就看kernel有没有支持按照"pid namespace"或者cgroup做这类统计了。但我Google了一下`cgroup aware loadavg`和`pid namespace aware loadavg`，`loadavg container`，似乎这方面内核还没有很好的支持，唯一关联性较强的一个信息是14年有人在尝试实现`cgroup aware proc`（见[链接](http://www.spinics.net/lists/cgroups/msg09971.html)），虽然理论上有可行的办法，但因此带来的开销也会增加不少。

如果内核本身没有直接支持的话，想办法在用户态计算`/proc/loadavg`内的值就难了（不像memory， 可以直接在cgroup下读到，inject.so只是做下格式转换）。

**Comment by liuflylove666** [comment]
我想咨询一下，你们针对Docker的监控是怎么做的，都有哪些指标。

**Comment by jizhilong** [comment]
@ljpsfree

**Comment by ljpsfree** [comment]
如果是监控的话，我们是做在宿主机上面的。宿主机上可以通过cgroup读取到正确的值,不过cgroup的行为跟内核有一定的关系，要使用最新的内核。这个方案我们之前是用来让用户在容器内部读取到正确的系统值的，但是目前我们换了lxcfs的方案。

**Comment by liuflylove666** [comment]
请问lxcfs你有做过二次开发吗？

**Comment by jizhilong** [comment]
http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html
有兴趣可以看看BrandenGregg这篇介绍loagavg的文章，事实上，从很早(20多年前)开始，Linux上loadavg的定义就不只是CPU load那么单纯了，更应该称之为system load, 而且这个指标的绝对值意义也不大（变化趋势才有）。而且在内核本身不支持的情况下，想要通过其他数据间接计算每隔cgroup下的loadavg，几乎是不可能的。

既然loadavg一方面是一个system wide的metric，另一方面又难以进行per-cgroup的 计算。不如索性不要在容器上监控这个值，转而使用其他更精确，定义更明确的指标。
